import { describe, it, expect } from 'vitest'
import {
  buildSnapshot, buildSyncScript, columnDefinition, compareSchemas, defaultSelection, isSelectable,
  DEFAULT_SYNC_OPTIONS,
  type PgColumn, type PgTable, type SchemaSnapshot, type SnapshotRows, type SyncItem,
} from './structure-sync'

const col = (name: string, type: string, extra: Partial<PgColumn> = {}): PgColumn => ({
  name, type, notNull: false, default: null, generated: null, identity: '', serial: false, ...extra,
})

const usersTable = (): PgTable => ({
  name: 'users',
  columns: [
    col('id', 'integer', { notNull: true, default: "nextval('users_id_seq'::regclass)", serial: true }),
    col('email', 'text', { notNull: true }),
  ],
  constraints: [{ name: 'users_pkey', type: 'p', definition: 'PRIMARY KEY (id)' }],
  indexes: [{ name: 'users_email_idx', unique: true, only: false, body: 'USING btree (email)' }],
})

const postsTable = (): PgTable => ({
  name: 'posts',
  columns: [col('id', 'bigint', { notNull: true, identity: 'a' }), col('user_id', 'integer')],
  constraints: [
    { name: 'posts_pkey', type: 'p', definition: 'PRIMARY KEY (id)' },
    { name: 'posts_user_id_fkey', type: 'f', definition: 'FOREIGN KEY (user_id) REFERENCES users(id)', refTable: 'users' },
  ],
  indexes: [],
})

const snapshot = (partial: Partial<SchemaSnapshot>): SchemaSnapshot => ({ tables: [], views: [], enums: [], extensions: [], ...partial })
const item = (items: SyncItem[], key: string) => items.find(i => i.key === key)!

describe('columnDefinition', () => {
  it('renders serial, identity, generated, default and NOT NULL columns', () => {
    expect(columnDefinition(usersTable().columns[0])).toBe('"id" serial')
    expect(columnDefinition(col('id', 'bigint', { notNull: true, identity: 'd' }))).toBe('"id" bigint GENERATED BY DEFAULT AS IDENTITY')
    expect(columnDefinition(col('total', 'numeric', { generated: 'price * qty' }))).toBe('"total" numeric GENERATED ALWAYS AS (price * qty) STORED')
    expect(columnDefinition(col('state', 'text', { notNull: true, default: "'new'::text" }))).toBe(`"state" text DEFAULT 'new'::text NOT NULL`)
  })
})

describe('buildSnapshot', () => {
  it('assembles tables, strips the table name from index definitions, and maps view dependencies', () => {
    const rows: SnapshotRows = {
      tables: [{ table_name: 'users' }],
      columns: [{ table_name: 'users', name: 'id', type: 'integer', not_null: true, default_expr: "nextval('users_id_seq'::regclass)", generated_expr: null, identity: '', owns_sequence: true }],
      constraints: [{ table_name: 'users', name: 'users_pkey', type: 'p', definition: 'PRIMARY KEY (id)', ref_table: null }],
      indexes: [{ table_name: 'users', name: 'users_lower_idx', definition: 'CREATE UNIQUE INDEX users_lower_idx ON app.users USING btree (lower(email))', qualified_table: 'app.users', quoted_table: 'users' }],
      views: [{ name: 'active_users', definition: ' SELECT id FROM users;' }],
      viewDeps: [{ view_name: 'active_users', depends_on: 'users' }],
      enums: [{ name: 'mood', values: ['sad', 'happy'] }],
      extensions: [{ name: 'uuid-ossp', schema: 'public', in_schema: false }],
    }
    const snap = buildSnapshot(rows)
    expect(snap.extensions).toEqual([{ name: 'uuid-ossp', schema: 'public', inSchema: false }])
    expect(snap.tables[0].columns[0].serial).toBe(true)
    expect(snap.tables[0].indexes[0]).toEqual({ name: 'users_lower_idx', unique: true, only: false, body: 'USING btree (lower(email))' })
    expect(snap.views[0]).toEqual({ name: 'active_users', definition: 'SELECT id FROM users', dependsOn: ['users'] })
    expect(snap.enums[0].values).toEqual(['sad', 'happy'])
  })
})

describe('compareSchemas', () => {
  it('creates missing tables with foreign keys deferred until every table exists', () => {
    const items = compareSchemas(snapshot({ tables: [usersTable(), postsTable()] }), snapshot({}), 'staging')
    const script = buildSyncScript(items, defaultSelection(items), 'staging')
    expect(script).toContain('BEGIN;\nSET LOCAL search_path TO "staging", public;')
    expect(script.trim().endsWith('COMMIT;')).toBe(true)
    expect(script).not.toContain('-- Part')
    expect(script).toContain('CREATE TABLE "staging"."users" (\n  "id" serial,\n  "email" text NOT NULL,\n  CONSTRAINT "users_pkey" PRIMARY KEY (id)\n)')
    expect(script).toContain('CREATE UNIQUE INDEX "users_email_idx" ON "staging"."users" USING btree (email)')
    const fk = script.indexOf('ADD CONSTRAINT "posts_user_id_fkey"')
    expect(fk).toBeGreaterThan(script.indexOf('CREATE TABLE "staging"."posts"'))
    expect(fk).toBeGreaterThan(script.indexOf('CREATE TABLE "staging"."users"'))
  })

  it('reports identical tables as same, even when a constraint only differs by name', () => {
    const target = usersTable()
    target.constraints = [{ name: 'users_pk_renamed', type: 'p', definition: 'PRIMARY KEY (id)' }]
    const items = compareSchemas(snapshot({ tables: [usersTable()] }), snapshot({ tables: [target] }), 'public')
    expect(item(items, 'table:users').action).toBe('same')
    expect(isSelectable(item(items, 'table:users'))).toBe(false)
  })

  it('alters changed columns in type → default → not null order', () => {
    const source = usersTable()
    source.columns.push(col('status', 'character varying(20)', { notNull: true, default: "'active'::character varying" }))
    const target = usersTable()
    target.columns.push(col('status', 'text'))
    const t = item(compareSchemas(snapshot({ tables: [source] }), snapshot({ tables: [target] }), 'public'), 'table:users')
    expect(t.action).toBe('modify')
    expect(t.statements.map(s => s.sql)).toEqual([
      'ALTER TABLE "public"."users" ALTER COLUMN "status" TYPE character varying(20) USING "status"::character varying(20)',
      `ALTER TABLE "public"."users" ALTER COLUMN "status" SET DEFAULT 'active'::character varying`,
      'ALTER TABLE "public"."users" ALTER COLUMN "status" SET NOT NULL',
    ])
  })

  it('keeps target-only columns unless dropping is enabled', () => {
    const target = usersTable()
    target.columns.push(col('legacy', 'text'))
    const kept = item(compareSchemas(snapshot({ tables: [usersTable()] }), snapshot({ tables: [target] }), 'public'), 'table:users')
    expect(kept.action).toBe('same')
    expect(kept.notes[0]).toMatch(/legacy exists only in the target/)

    const dropped = item(compareSchemas(snapshot({ tables: [usersTable()] }), snapshot({ tables: [target] }), 'public', { ...DEFAULT_SYNC_OPTIONS, dropColumns: true }), 'table:users')
    expect(dropped.statements.map(s => s.sql)).toEqual(['ALTER TABLE "public"."users" DROP COLUMN "legacy"'])
  })

  it('warns when adding a NOT NULL column with no default', () => {
    const source = usersTable()
    source.columns.push(col('name', 'text', { notNull: true }))
    const t = item(compareSchemas(snapshot({ tables: [source] }), snapshot({ tables: [usersTable()] }), 'public'), 'table:users')
    expect(t.statements[0].sql).toBe('ALTER TABLE "public"."users" ADD COLUMN "name" text NOT NULL')
    expect(t.warnings.join()).toMatch(/fails if the target table has rows/)
  })

  it('drops and re-adds changed constraints and indexes', () => {
    const source = usersTable()
    source.indexes = [{ name: 'users_email_idx', unique: true, only: false, body: 'USING btree (lower(email))' }]
    const target = usersTable()
    target.constraints.push({ name: 'users_email_check', type: 'c', definition: "CHECK (email <> ''::text)" })
    const sql = item(compareSchemas(snapshot({ tables: [source] }), snapshot({ tables: [target] }), 'public'), 'table:users').statements.map(s => s.sql)
    expect(sql).toContain('ALTER TABLE "public"."users" DROP CONSTRAINT IF EXISTS "users_email_check"')
    expect(sql).toContain('DROP INDEX IF EXISTS "public"."users_email_idx"')
    expect(sql).toContain('CREATE UNIQUE INDEX "users_email_idx" ON "public"."users" USING btree (lower(email))')
  })

  it('marks serial vs plain differences as manual, but still syncs the rest of the table', () => {
    const source = usersTable()
    source.columns.push(col('age', 'integer'))
    const target = usersTable()
    target.columns[0] = col('id', 'integer', { notNull: true })
    const t = item(compareSchemas(snapshot({ tables: [source] }), snapshot({ tables: [target] }), 'public'), 'table:users')
    expect(t.unsupported).toBe(true)
    expect(t.statements.map(s => s.sql)).toEqual(['ALTER TABLE "public"."users" ADD COLUMN "age" integer'])
    expect(isSelectable(t)).toBe(true)
  })

  it('lists target-only tables as unselected drops that first remove foreign keys pointing at them', () => {
    const items = compareSchemas(snapshot({}), snapshot({ tables: [usersTable(), postsTable()] }), 'public')
    const users = item(items, 'table:users')
    expect(users.action).toBe('drop')
    expect(defaultSelection(items)).toEqual([])
    const script = buildSyncScript(items, [users.key], 'public')
    expect(script.indexOf('DROP CONSTRAINT IF EXISTS "posts_user_id_fkey"')).toBeLessThan(script.indexOf('DROP TABLE "public"."users"'))
  })

  it('adds new enum values in position and refuses removed/reordered values', () => {
    const added = item(compareSchemas(
      snapshot({ enums: [{ name: 'mood', values: ['sad', 'ok', 'happy', 'ecstatic'] }] }),
      snapshot({ enums: [{ name: 'mood', values: ['sad', 'happy'] }] }), 'public'), 'enum:mood')
    expect(added.statements.map(s => s.sql)).toEqual([
      `ALTER TYPE "public"."mood" ADD VALUE 'ok' BEFORE 'happy'`,
      `ALTER TYPE "public"."mood" ADD VALUE 'ecstatic'`,
    ])
    // Enum values get their own transaction, committed before anything that might use them
    const items = compareSchemas(
      snapshot({ enums: [{ name: 'mood', values: ['sad', 'ok'] }], tables: [usersTable()] }),
      snapshot({ enums: [{ name: 'mood', values: ['sad'] }] }), 'public')
    const script = buildSyncScript(items, items.map(i => i.key), 'public')
    const part2 = script.indexOf('-- Part 2 of 2')
    expect(script.indexOf(`ADD VALUE 'ok'`)).toBeLessThan(script.indexOf('COMMIT;'))
    expect(script.indexOf('COMMIT;')).toBeLessThan(part2)
    expect(script.indexOf('CREATE TABLE')).toBeGreaterThan(part2)

    const reordered = item(compareSchemas(
      snapshot({ enums: [{ name: 'mood', values: ['happy', 'sad'] }] }),
      snapshot({ enums: [{ name: 'mood', values: ['sad', 'happy'] }] }), 'public'), 'enum:mood')
    expect(reordered.unsupported).toBe(true)
    expect(isSelectable(reordered)).toBe(false)
  })

  it('creates views after their dependencies and drops dependents first', () => {
    const views = [
      { name: 'b_summary', definition: 'SELECT count(*) FROM a_active', dependsOn: ['a_active'] },
      { name: 'a_active', definition: 'SELECT * FROM users', dependsOn: [] },
    ]
    const created = compareSchemas(snapshot({ views }), snapshot({}), 'public')
    const createScript = buildSyncScript(created, defaultSelection(created), 'public')
    expect(createScript.indexOf('VIEW "public"."a_active"')).toBeLessThan(createScript.indexOf('VIEW "public"."b_summary"'))

    const dropped = compareSchemas(snapshot({}), snapshot({ views }), 'public')
    const dropScript = buildSyncScript(dropped, dropped.map(i => i.key), 'public')
    expect(dropScript.indexOf('DROP VIEW "public"."b_summary"')).toBeLessThan(dropScript.indexOf('DROP VIEW "public"."a_active"'))
  })

  it('recreates changed views, replacing in place only when other views depend on them', () => {
    const src = [{ name: 'v', definition: 'SELECT id, email FROM users', dependsOn: [] }]
    const old = { name: 'v', definition: 'SELECT id FROM users', dependsOn: [] }
    const recreated = item(compareSchemas(snapshot({ views: src }), snapshot({ views: [old] }), 'public'), 'view:v')
    expect(recreated.statements.map(s => s.sql)).toEqual(['DROP VIEW "public"."v"', 'CREATE VIEW "public"."v" AS\nSELECT id, email FROM users'])

    const dependent = { name: 'w', definition: 'SELECT * FROM v', dependsOn: ['v'] }
    const replaced = item(compareSchemas(snapshot({ views: src }), snapshot({ views: [old, dependent] }), 'public'), 'view:v')
    expect(replaced.statements.map(s => s.sql)).toEqual(['CREATE OR REPLACE VIEW "public"."v" AS\nSELECT id, email FROM users'])
    expect(replaced.warnings[0]).toMatch(/Other views depend on this one \(w\)/)

    const same = item(compareSchemas(snapshot({ views: src }), snapshot({ views: [{ name: 'v', definition: 'SELECT id,\n   email FROM users', dependsOn: [] }] }), 'public'), 'view:v')
    expect(same.action).toBe('same')
  })

  it('installs extensions missing from the target before the objects that use them', () => {
    const table: PgTable = { name: 'tokens', columns: [col('id', 'uuid', { notNull: true, default: 'uuid_generate_v4()' })], constraints: [], indexes: [] }
    const items = compareSchemas(
      snapshot({ tables: [table], extensions: [{ name: 'uuid-ossp', schema: 'public', inSchema: false }] }),
      snapshot({}), 'app')
    const ext = item(items, 'extension:uuid-ossp')
    expect(ext.action).toBe('create')
    expect(defaultSelection(items)).toContain(ext.key)
    const script = buildSyncScript(items, defaultSelection(items), 'app')
    expect(script.indexOf('CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA "public"')).toBeLessThan(script.indexOf('CREATE TABLE'))
  })

  it('installs an extension that lives in the source schema into the target schema', () => {
    const [ext] = compareSchemas(snapshot({ extensions: [{ name: 'citext', schema: 'app', inSchema: true }] }), snapshot({}), 'app_copy')
    expect(ext.statements[0].sql).toBe('CREATE EXTENSION IF NOT EXISTS "citext" SCHEMA "app_copy"')
  })

  it('flags extensions installed where the target schema cannot see them, and ignores matching ones', () => {
    const src = snapshot({ extensions: [{ name: 'uuid-ossp', schema: 'public', inSchema: false }, { name: 'hstore', schema: 'public', inSchema: false }] })
    const dst = snapshot({ extensions: [{ name: 'uuid-ossp', schema: 'other', inSchema: false }, { name: 'hstore', schema: 'public', inSchema: false }] })
    const items = compareSchemas(src, dst, 'app')
    expect(items.map(i => i.key)).toEqual(['extension:uuid-ossp'])
    expect(items[0].unsupported).toBe(true)
    expect(items[0].warnings[0]).toMatch(/ALTER EXTENSION "uuid-ossp" SET SCHEMA "public"/)
    expect(isSelectable(items[0])).toBe(false)
  })

  it('respects the object type filters and returns an empty script when nothing is selected', () => {
    const items = compareSchemas(snapshot({ tables: [usersTable()], enums: [{ name: 'mood', values: ['a'] }] }), snapshot({}), 'public', { ...DEFAULT_SYNC_OPTIONS, tables: false })
    expect(items.map(i => i.key)).toEqual(['enum:mood'])
    expect(buildSyncScript(items, [], 'public')).toBe('')
  })
})
